# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aGRz9cIua-YyRQgcDmqQw3JnUrc3FIMk
"""

#JHULIET CONZA
#EJERCICIO 3

import sympy as sp
#Ejericios de clase

A = np.array([[2, 1],
              [0, 3]])

B = np.array([[1, 2],
              [3, 0]])

print("La suma matricial es \n", A+B)
print("EL producto matricial es \n", A*B)
 #Inversa de A
if np.linalg.det(A) != 0:
    print("La inversa de A es\n", np.linalg.inv(A))
else:
    print("La matriz no tiene inversa porque su determinante es cero.")
#Determinante de B
print("El determinante de B es: ", np.linalg.det(B))

u = [1, 3]
v = [-1, 2]
print("El producto punto es: ", np.dot(u,v))
print(f"La magnitud de u es: {np.linalg.norm(u):.2f}")
print(f"La magnitud de v es: {np.linalg.norm(v):.2f}")

#Derivadas
x = sp.Symbol('x')
h = sp.sin(2*x**2 + 3*x)

dh = sp.diff(h, x)

print("h(x) =", h)
print("h'(x) =", dh)
#Evaluar en h'(1) y h'(0)
print("h'(1) =", dh.subs(x, 1))
print("h'(0) =", dh.subs(x, 0))